### ISSUE TITLE
Support GPU processing

### ISSUE THREAD

**Issue by niskov** [ksasao/YoloSharp#1]
Couldn't find configuration to run this over GPU (cuda)

**Comment by niskov** [comment]
I've committed the fix

**Comment by tinohager** [comment]
@niskov You can use [Alturos.Yolo](https://github.com/AlturosDestinations/Alturos.Yolo) this project have gpu support for cuda

**Comment by ksasao** [comment]
Now you can use GPU-acceleration option with SetPreferableTarget(). It support various CPU/GPU such as NVIDIA, AMD and Intel  with FP16. You can also use SetPreferableBackend(), it allows to use Intel's Deep Learning Inference Engine (OpenVINO).
