### ISSUE TITLE
Support gpu? 

### ISSUE THREAD

**Issue by nurmanhariyanto** [ksasao/YoloSharp#4]

**Comment by tinohager** [comment]
@nurmanhariyanto You can use [Alturos.Yolo](https://github.com/AlturosDestinations/Alturos.Yolo) this project have gpu support for cuda

**Comment by ksasao** [comment]
Now you can use GPU-acceleration option with SetPreferableTarget(). It support various CPU/GPU such as NVIDIA, AMD and Intel  with FP16. You can also use SetPreferableBackend(), it allows to use Intel's Deep Learning Inference Engine (OpenVINO).
