### ISSUE TITLE
Can I use multiple networks?

### ISSUE THREAD

**Issue by takai-hiromu** [ksasao/YoloSharp#5]
I want to use two different networks at the one project.
But , this lib seems to run only one network model.
What should I do?

**Comment by ksasao** [comment]
Thank you for reporting. I fix the issue. 

See https://github.com/ksasao/YoloSharp/commit/57722e2f0db9efc7c7653beceb5fe756aa5f3957#diff-f7b8aba99ea3bf3399f9c0e9975555f4

Please replace old YoloSharp.h to [this one](https://github.com/ksasao/YoloSharp/blob/29c7fa89190855ff9533536806f513eb8565bff6/src/YoloSharp/YoloSharp.h).
You don't neet to change other files.

**Comment by ksasao** [comment]
I fixed some bugs and added .sln/.vcxproj for Visual Studio 2015.
